### ISSUE TITLE
Make different ArrayList for Start Date and End Date of project tasks.

### ISSUE THREAD

**Issue by atiqueahmedziad** [atiqueahmedziad/Easy-Project-Management-Tool#9]
## Step to reproduce
I have used a single Arraylist to store the Start Dates and End Dates of all tasks inside a project [look here](https://github.com/atiqueahmedziad/Easy-Project-Management-Tool/blob/4ca0bd9b71fc0f07b3ab0c9372efe11ade941f64/src/App/ProjectDetail/ProjectDetailController.java#L466-L467) and looped through them periodically to get expected result.  [Look here](https://github.com/atiqueahmedziad/Easy-Project-Management-Tool/blob/4ca0bd9b71fc0f07b3ab0c9372efe11ade941f64/src/App/ProjectDetail/ProjectDetailController.java#L523-L531)

It is better we use 2 Arraylist to contain Start Date and End Date.

**Comment by Vignesh-Durairaj** [comment]
Raised a pull request to merge code from my [fork](https://github.com/Vignesh-Durairaj/Easy-Project-Management-Tool) to your master branch. Kindly review and merge the same.

Note : My first contribution to an outsider's project.

**Comment by atiqueahmedziad** [comment]
@Vignesh-Durairaj  PR Merged! Thank you for your contribution.
